sudo: false

language: php

php:
  - 7.0
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - deps=no

install:
  - if [ "$deps" = "no" ]; then composer install; fi;
  - if [ "$deps" = "low" ]; then composer --prefer-lowest --prefer-stable update; fi;

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit

before_install:
  - composer self-update
